[package]
name = "orynt-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
anyhow.workspace = true
orynt-storage = { path = "../../../crates/storage", version = "=0.1.0" }
serde.workspace = true
tauri.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
